name: Armbian Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install git

    - name: Clone Armbian repository
      run: |
        git clone --depth=1 --branch=main https://github.com/armbian/build
        cd build

    - name: Print Working Directory
      run: |
        pwd

    - name: Print list
      working-directory: build
      run: |
        ls -la

    - name: Run compile.sh
      working-directory: build
      run: |
          ./compile.sh \
          BOARD=hinlink-h88k \
          BRANCH=legacy \
          RELEASE=jammy \
          BUILD_MINIMAL=no \
          BUILD_DESKTOP=yes \
          KERNEL_CONFIGURE=no

    - name: Generate release tag
      id: tag
      run: |
        echo "::set-output name=release_tag::UserBuild_$(date +"%Y.%m.%d_%H-%M")"

    - name: Upload release artifacts
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        working-directory: build/output/images
        files: |
          /*
        token: ${{ secrets.GHH_CI_TOKEN }}
        release_name: Release ${{ github.run_number }}
        
