name: Armbian Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install git

    - name: Clone Armbian repository
      run: |
        git clone --depth=1 --branch=main https://github.com/armbian/build
        cd build

    - name: Run compile.sh
      working-directory: build
      run: |
          ./compile.sh \
          BOARD=hinlink-h88k \
          BRANCH=legacy \
          RELEASE=jammy \
          BUILD_MINIMAL=yes \
          BUILD_DESKTOP=no \
          KERNEL_CONFIGURE=no

    - name: Packfiles
      working-directory: build
      run: |
          tar -czvf pack_images.tar.gz ./output/images/*.img
          #tar -czvf pack_output.tar.gz ./output/
          mkdir dl_output
          #mv pack_images.tar.gz ./up_output/
          #mv pack_output.tar.gz ./up_output/

    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: Pack_Output
        path: |
          build/output/images/*.img
          build/pack_images.tar.gz
          build/up_output/
