name: Armbian Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install git

    - name: Clone Armbian repository
      run: |
        git clone --depth=1 --branch=main https://github.com/armbian/build
        cd build

    - name: Run compile.sh T1
      working-directory: build
      run: |
          ./compile.sh \
          BOARD=hinlink-h88k \
          BRANCH=legacy \
          RELEASE=jammy \
          BUILD_MINIMAL=yes \
          BUILD_DESKTOP=no \
          KERNEL_CONFIGURE=no

    - name: Packfiles
      working-directory: build
      run: |
          #tar -czvf pack_images.tar.gz ./output/images/*.img
          tar -czvf armbian_output.tar.gz ./armbian/output/
          tar -czvf pack_output.tar.gz ./output/
          mkdir dl_output
          #mv pack_images.tar.gz ./up_output/
          #mv armbian_output.tar.gz ./up_output/
          #mv pack_output.tar.gz ./up_output/
          

    - name : Upload action artifact
      uses: actions/upload-artifact@master
      with:
        name: Pack_Output
        path: |
          build/armbian_output.tar.gz
          build/pack_images.tar.gz
          
    - name: Generate release tag
      id: tag
      run: |
        echo "::set-output name=release_tag::UserBuild_$(date +"%Y.%m.%d_%H-%M")"
        
    - name: Upload release artifacts
      uses: softprops/action-gh-release@v1
      #if: startsWith(github.ref, 'refs/tags/')
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        files: |
          build/output/images/*.img
        token: ${{ secrets.GHH_CI_TOKEN }}
