name: Armbian Build and Release Eedge

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install git neofetch
        sudo apt-get autoremove && sudo apt-get clean

    - name: Install dependencies
      run: |
        lscpu
        df -h
        neofetch --off

    - name: Clone Armbian repository
      run: |
        git clone --depth=1 --branch=main https://github.com/ChunHungHK/Armbian_build
        cd Armbian_build

    - name: Run compile.sh
      working-directory: Armbian_build
      run: |
          ./compile.sh \
          BOARD=hinlink-h88k \
          BRANCH=edge \
          RELEASE=jammy \
          BUILD_MINIMAL=yes \
          COMPRESS_OUTPUTIMAGE="sha,gz" \
          REPOSITORY_INSTALL=armbian-desktop \
          KERNEL_CONFIGURE=no

    - name : Upload action artifact
      uses: actions/upload-artifact@master
      with:
        name: Pack_Output
        path: |
          Armbian_build/output/

    - name: Packfiles
      working-directory: Armbian_build
      run: |
        tar -cvf pack_images.tar /output/images
          
    - name: Generate release tag
      id: tag
      run: |
        echo "::set-output name=release_tag::Armbian-unofficial-h88k-jammy_$(date +"%Y.%m.%d_%H-%M")"
        
    - name: Upload release artifacts
      uses: softprops/action-gh-release@v1
      #if: startsWith(github.ref, 'refs/tags/')
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        files: |
          Armbian_build/pack_images.tar
        token: ${{ secrets.GHH_CI_TOKEN }}
